@baseUrl = http://localhost:3333
@authToken = {{Authenticate.response.body.access_token}}

# @name Create_deliveryman
POST {{baseUrl}}/deliveryman
Content-Type: application/json

{
    "name": "samuel molinari deliveryman",
    "cpf": "12556522925",
    "password": "123456"
}


###


# @name Authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "cpf": "12431291231",
    "password": "123456"
}

###




